version: '3.1'
services:
  mongodb:
    # user: "nfsnobody" # insert either uid or name of the user
    image: mongo:3.6
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: exemplo

  mongo-shell:
    image: mongo:3.6
    container_name: meu-mongodb-shell
    command: ["mongo", "--host", "mongodb", "-u", "root", "-p", "exemplo", "--authenticationDatabase", "admin"]
    depends_on:
      - mongodb